"""
This type stub file was generated by cyright.
"""

from enum import IntEnum
from typing import Any


class BroadcastMode(IntEnum):
    SPSC = ...
    SPMC = ...
    MPSC = ...
    MPMC = ...


class BroadcastQueue:
    def __init__(
            self, 
            capacity: int,
            mode: BroadcastMode = BroadcastMode.SPSC,
            overwrite: bool = False,
            block_on_full: bool = False
            ) -> None:
        ...
    
    def push(self, msg: object) -> int:
        ...
    
    def try_push(self, msg: object) -> int:
        ...
    
    def pop(self) -> object:
        ...
    
    def try_pop(self) -> object:
        ...
    
    def register_consumer(self) -> int:
        ...
    
    def unregister_consumer(self) -> Any:
        ...
    
    def register_producer(self) -> int:
        ...
    
    def unregister_producer(self) -> Any:
        ...
    
    def close(self, timeout_ms: int = ...) -> int:
        ...
    


